config/routes.rb
Portfolio::Application.routes.draw do
  
  root 'pages#about'
  
  match '/resume' => 'pages#resume', :via => [:get] #resume_path
  match '/experiences' => 'pages#experiences', :via => [:get]
  match '/blog' => 'pages#blog', :via => [:get]
  match '/FAQs' => 'pages#faqs', :via => [:get], :as => 'faqs'
  match '/skills' => 'pages#skills', :via => [:get]
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  #in case if filtering needs to be done with ip_address and session hash
  #:unique => [:ip_address, :session_hash]
  impressionist :unique => [:ip_address]
  
  def about
    @impressions = Impression.count
  end
  
  def resume
  end
  
  def experiences
  end
  
  def blog
  end
  
  def faqs
  end
  
  def skills
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_contact.html.erb
<div id="name">
</div>

app/views/layouts/_footer.html.erb
<footer>
	<div id="copyright">&copy; Purushottam Thapa <%=Time.now.year%>.</div>
	<div id="wrapper">
		<div id="left">
			<span>Address</span><br/>
			<p>Siltapellonkuja 2 R 142</p>
			00740, Helsinki<br/>
			Finland.
		</div>
		<hr width="1.5" size="100">
		<div id="right">
			<span>Contact</span><br/>
			<p>Email: Purushottam.ThapaMagar@gmail.com</p>
			Phone: +358 443622069
		</div>
	</div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="round">
	<ul>
		<li><%= link_to('About', root_path) %></li>|
		<li><%= link_to('Resume', resume_path) %></li>|
		<li><%= link_to('Experiences', experiences_path) %></li>|
		<li><%= link_to('Skills', skills_path)%></li>
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Purushot | <%= @page_title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<header>
			<%= render 'layouts/contact' %>
				<%= render 'layouts/navigation' %>
		</header>
		<section class="round">
			<%= yield %>
		</section>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<% @page_title = "About" %>

<div id="image_container">
  <img src="assets/profile.png" />
  <h2>Who Am I</h2>  
</div>

<p id="intro">I am Purushottam Thapa (Puru), a postgrad student at the Department of Computer Science in University of Helsinki.
I am also a graduate of Metropolia UAS in Media Engineering. I am 
a Vim fan(atic) and I hope to develop some plugin for Vim in future. My other interests include discrete algorithms, AI, big data, machine learning, computational
biology and lambda calculus.
</p>
<div id="list_div">
  I endorse:
  <ul id="elist">
      <li>Python/Ruby/PHP</li>
      <li>Ruby on Rails</li>   
      <li>ReactJs </li>
      <li>Git</li>
      <li>Adobe Illustrator</li>
      <li>MVim - my editor of choice </li>
  </ul>
</div>
<p id="counter"><%= @impressions %></p>

app/views/pages/blog.html.erb
<% @page_title = 'Blog' %>
<p>Haven't found any interesting yet.</p>

app/views/pages/experiences.html.erb
<% @page_title = 'Experiences' %>
Projects >>
<div class="expCapsul">
  <span class="expHeader"><%=link_to("Analysis of Refugee Migration Patterns", "https://hcorinna.github.io/refugee-migration-patterns/")%></span> | <span class="expHeader"><%= link_to("Source Code", "https://github.com/hcorinna/refugee-migration-patterns")%></span><br/>
</div>
<div class="expCapsul">
  <span class="expHeader"><%=link_to("Ratebeer App", "https://rate-beer.herokuapp.com/")%></span> | <span class="expHeader"><%= link_to("Source Code", "https://github.com/gorupria/ratebeer")%></span><br/>
</div>
<div class="expCapsul">
<span class="expHeader">Korjausurakka</span><br/>
<div class="expInfo round">
	Employer: Dooxe Oy<br/>
	Duration: 4 months<br/>
	Role: Front/Back-end web-developer<br/>
	Tasks:
	<ul>
		<li>Wrote front and back-end code using HTML, CSS and PHP</li>
		<li>Zend-framework was used as a basic foundation</li>
	</ul>
</div>
</div>

<div class="expCapsul">
<span class="expHeader">Swengi</span><br/>
<div class="expInfo round">
	Employer: Metropolia UAS<br/>
	Duration: 4 months<br/>
	Role: Back-end developer, iOS developer<br/>
	Tasks:
	<ul>
		<li>Used Scrum as a software development methodology.</li>
		<li>Created back-end of an iPhone application using PHP.</li>
		<li>Managed MySQL Database.</li>
		<li>Did iOS Programming.</li>
	</ul>
</div>
</div>

<div class="expCapsul">
<span class="expHeader">Location Based Services(LBS)</span><br/>
<div class="expInfo round">
	Employer: Metropolia UAS<br/>
	Duration: 4 months<br/>
	Role: Front/Back-end web-developer, iOS developer<br/>
	Tasks:
	<ul>
		<li>Used Scrum as a software development methodology.</li>
		<li>Designed and managed server-side MYSQL database.</li>
		<li>Wrote server-side code for iPhone application.</li>
		<li>Did some iOS client-side coding</li> 
	</ul>
</div>
</div>

<div class="expCapsul">
  <span class="expHeader">Entrepreneur (2014-2017)</span>
  <div class="expInfo round">CEO at Shreeganesh Oy.</div>
</div>

app/views/pages/resume.html.erb
<% @page_title = "Resume" %>
<p>Get my resume by clicking on the link below.</p>
<%= link_to("Download CV","CV.pdf", :class => "resume") %>

app/views/pages/skills.html.erb
<% @page_title = "Skills" %>

<p><strong>The full list of what I can do. </strong></p>
<ul>
  <li>HTML, CSS, SASS</li>
	<li>Ruby on Rails</li>
	<ul>
		<li>Test Driven Development(TDD) with RSpec</li>
	</ul>
  <li>React</li>
  <li>D3</li>
  <li>Python(pandas, numpy, matlibplot)</li>
  <li>Docker</li>
	<li>ASP.NET</li>
	<li>PHP</li>
  <li>Bootstrap</li>
  <li>Bourbon.io</li>
	<li>SQL</li>
	<li>JQuery</li>
  <li>Ruby</li>
  <li>C-Programming</li>
  <li>R-Programming</li>
	<li>Database Design and Management</li>
	<li>Git</li>
	<li>Scrum</li>
	<li>JavaScript</li>
	<li>Haskell</li>
  <li>Adobe Photoshop</li>
	<li>AJAX</li>
	<li>Drupal</li>
</ul>